/**
 * Permission keys the UI checks — a mirror of the backend catalog
 * (src/permissions/permissions.catalog.ts). The UI only hides what the user
 * cannot do; the API enforces every permission itself.
 */
export const P = {
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',
  BRANCH_READ: 'branch.read',
  BRANCH_CREATE: 'branch.create',
  BRANCH_UPDATE: 'branch.update',
  SUB_CENTERS_READ: 'sub_centers.read',
  SUB_CENTERS_MANAGE: 'sub_centers.manage',
  ANALYTICS_CENTER_READ: 'analytics.center.read',
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  FAMILIES_READ: 'families.read',
  FAMILIES_CREATE: 'families.create',
  FAMILIES_UPDATE: 'families.update',
  FAMILIES_DELETE: 'families.delete',
  STUDENTS_READ: 'students.read',
  STUDENTS_READ_OWN: 'students.read_own',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_UPDATE: 'students.update',
  STUDENTS_DELETE: 'students.delete',
  COURSES_READ: 'courses.read',
  COURSES_CREATE: 'courses.create',
  COURSES_UPDATE: 'courses.update',
  COURSES_DELETE: 'courses.delete',
  GROUPS_READ: 'groups.read',
  GROUPS_READ_OWN: 'groups.read_own',
  GROUPS_CREATE: 'groups.create',
  GROUPS_UPDATE: 'groups.update',
  GROUPS_DELETE: 'groups.delete',
  ENROLLMENTS_READ: 'enrollments.read',
  ENROLLMENTS_CREATE: 'enrollments.create',
  ENROLLMENTS_UPDATE: 'enrollments.update',
  ENROLLMENTS_TRANSFER: 'enrollments.transfer',
  ENROLLMENTS_CANCEL: 'enrollments.cancel',
  TEACHERS_READ: 'teachers.read',
  TEACHERS_CREATE: 'teachers.create',
  TEACHERS_UPDATE: 'teachers.update',
  TEACHERS_DELETE: 'teachers.delete',
  ROOMS_READ: 'rooms.read',
  ROOMS_CREATE: 'rooms.create',
  ROOMS_UPDATE: 'rooms.update',
  ROOMS_DELETE: 'rooms.delete',
  SCHEDULES_MANAGE: 'schedules.manage',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_READ_OWN: 'attendance.read_own',
  ATTENDANCE_MARK: 'attendance.mark',
  ATTENDANCE_MARK_OWN: 'attendance.mark_own',
  ATTENDANCE_MARK_FUTURE: 'attendance.mark_future',
  ATTENDANCE_DELETE: 'attendance.delete',
  FINANCE_READ: 'finance.read',
  FINANCE_INVOICE_CREATE: 'finance.invoice.create',
  FINANCE_INVOICE_UPDATE: 'finance.invoice.update',
  FINANCE_INVOICE_CANCEL: 'finance.invoice.cancel',
  FINANCE_PAYMENT_READ: 'finance.payment.read',
  FINANCE_PAYMENT_CREATE: 'finance.payment.create',
  FINANCE_CASH_READ: 'finance.cash.read',
  FINANCE_CASH_OPEN: 'finance.cash.open',
  FINANCE_CASH_CLOSE: 'finance.cash.close',
  FINANCE_EXPENSE_READ: 'finance.expense.read',
  FINANCE_EXPENSE_CREATE: 'finance.expense.create',
  FINANCE_EXPENSE_UPDATE: 'finance.expense.update',
  FINANCE_REFUND_CREATE: 'finance.refund.create',
  FINANCE_REPORT_READ: 'finance.report.read',
  LEADS_READ: 'leads.read',
  LEADS_CREATE: 'leads.create',
  LEADS_UPDATE: 'leads.update',
  LEADS_DELETE: 'leads.delete',
  LEADS_ASSIGN: 'leads.assign',
  LEADS_CONVERT: 'leads.convert',
  LEADS_ACTIVITY_READ: 'leads.activity.read',
  LEADS_ACTIVITY_CREATE: 'leads.activity.create',
  LEAD_SOURCES_READ: 'lead_sources.read',
  LEAD_SOURCES_MANAGE: 'lead_sources.manage',
  LEAD_PIPELINE_READ: 'lead_pipeline.read',
  LEAD_PIPELINE_MANAGE: 'lead_pipeline.manage',
  LEADS_REPORT_READ: 'leads.report.read',
  EMPLOYEES_READ: 'employees.read',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_UPDATE: 'employees.update',
  EMPLOYEES_DELETE: 'employees.delete',
  EMPLOYEE_BRANCHES_MANAGE: 'employee.branches.manage',
  POSITIONS_READ: 'positions.read',
  POSITIONS_MANAGE: 'positions.manage',
  DEPARTMENTS_READ: 'departments.read',
  DEPARTMENTS_MANAGE: 'departments.manage',
  TASKS_READ: 'tasks.read',
  TASKS_READ_OWN: 'tasks.read_own',
  TASKS_CREATE: 'tasks.create',
  TASKS_UPDATE: 'tasks.update',
  TASKS_UPDATE_OWN: 'tasks.update_own',
  TASKS_DELETE: 'tasks.delete',
  TASKS_ASSIGN: 'tasks.assign',
  TASKS_COMMENT: 'tasks.comment',
  TASKS_STATISTICS_READ: 'tasks.statistics.read',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  NOTIFICATION_PREFERENCES_READ: 'notification_preferences.read',
  NOTIFICATION_PREFERENCES_UPDATE: 'notification_preferences.update',
  NOTIFICATION_TEMPLATES_READ: 'notification_templates.read',
  NOTIFICATION_TEMPLATES_MANAGE: 'notification_templates.manage',
  NOTIFICATION_DELIVERY_READ: 'notification_delivery.read',
  NOTIFICATION_PROVIDERS_MANAGE: 'notification_providers.manage',
  AUDIT_READ: 'audit.read',
  DASHBOARD_READ: 'dashboard.read',
  REPORTS_ACADEMIC_READ: 'reports.academic.read',
} as const;

export type Permission = (typeof P)[keyof typeof P];

/** A route or action needs any one of these. */
export type PermissionRequirement = Permission | readonly Permission[];
