/**
 * Single source of truth for permission keys used in code (`@RequirePermissions`).
 * The database is the source of truth for *who* has them; the seed
 * (`src/database/seed.ts`) syncs this catalog into the `permissions` table.
 *
 * Add future modules here (finance.*, leads.* ...) and re-run the seed.
 *
 * `*_own` variants grant the same action restricted to groups the caller
 * teaches (Teacher.userId = caller). Routes accept either variant.
 */
export const PERMISSIONS = {
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',
  BRANCH_READ: 'branch.read',
  BRANCH_CREATE: 'branch.create',
  BRANCH_UPDATE: 'branch.update',
  /** Sub-centers (divisions of the center that group branches). */
  SUB_CENTERS_READ: 'sub_centers.read',
  /** Create, edit, freeze, activate and archive sub-centers. */
  SUB_CENTERS_MANAGE: 'sub_centers.manage',
  /** Staff accounts of the center (the spec's `staff.*`). */
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',

  FAMILIES_READ: 'families.read',
  FAMILIES_CREATE: 'families.create',
  FAMILIES_UPDATE: 'families.update',
  FAMILIES_DELETE: 'families.delete',
  STUDENTS_READ: 'students.read',
  STUDENTS_READ_OWN: 'students.read_own',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_UPDATE: 'students.update',
  STUDENTS_DELETE: 'students.delete',
  /** Covers courses and their levels. */
  COURSES_READ: 'courses.read',
  COURSES_CREATE: 'courses.create',
  COURSES_UPDATE: 'courses.update',
  COURSES_DELETE: 'courses.delete',
  GROUPS_READ: 'groups.read',
  GROUPS_READ_OWN: 'groups.read_own',
  GROUPS_CREATE: 'groups.create',
  GROUPS_UPDATE: 'groups.update',
  GROUPS_DELETE: 'groups.delete',
  ENROLLMENTS_READ: 'enrollments.read',
  ENROLLMENTS_CREATE: 'enrollments.create',
  ENROLLMENTS_UPDATE: 'enrollments.update',
  ENROLLMENTS_TRANSFER: 'enrollments.transfer',
  ENROLLMENTS_CANCEL: 'enrollments.cancel',
  TEACHERS_READ: 'teachers.read',
  TEACHERS_CREATE: 'teachers.create',
  TEACHERS_UPDATE: 'teachers.update',
  TEACHERS_DELETE: 'teachers.delete',
  ROOMS_READ: 'rooms.read',
  ROOMS_CREATE: 'rooms.create',
  ROOMS_UPDATE: 'rooms.update',
  ROOMS_DELETE: 'rooms.delete',
  SCHEDULES_MANAGE: 'schedules.manage',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_READ_OWN: 'attendance.read_own',
  ATTENDANCE_MARK: 'attendance.mark',
  ATTENDANCE_MARK_OWN: 'attendance.mark_own',
  ATTENDANCE_MARK_FUTURE: 'attendance.mark_future',
  ATTENDANCE_DELETE: 'attendance.delete',
  FINANCE_READ: 'finance.read',
  FINANCE_INVOICE_CREATE: 'finance.invoice.create',
  FINANCE_INVOICE_UPDATE: 'finance.invoice.update',
  FINANCE_INVOICE_CANCEL: 'finance.invoice.cancel',
  FINANCE_PAYMENT_READ: 'finance.payment.read',
  FINANCE_PAYMENT_CREATE: 'finance.payment.create',
  FINANCE_CASH_READ: 'finance.cash.read',
  FINANCE_CASH_OPEN: 'finance.cash.open',
  FINANCE_CASH_CLOSE: 'finance.cash.close',
  FINANCE_EXPENSE_READ: 'finance.expense.read',
  FINANCE_EXPENSE_CREATE: 'finance.expense.create',
  FINANCE_EXPENSE_UPDATE: 'finance.expense.update',
  FINANCE_REFUND_CREATE: 'finance.refund.create',
  FINANCE_REPORT_READ: 'finance.report.read',

  LEADS_READ: 'leads.read',
  LEADS_CREATE: 'leads.create',
  LEADS_UPDATE: 'leads.update',
  LEADS_DELETE: 'leads.delete',
  LEADS_ASSIGN: 'leads.assign',
  LEADS_CONVERT: 'leads.convert',
  LEADS_ACTIVITY_READ: 'leads.activity.read',
  LEADS_ACTIVITY_CREATE: 'leads.activity.create',
  LEAD_SOURCES_READ: 'lead_sources.read',
  LEAD_SOURCES_MANAGE: 'lead_sources.manage',
  LEAD_PIPELINE_READ: 'lead_pipeline.read',
  LEAD_PIPELINE_MANAGE: 'lead_pipeline.manage',
  LEADS_REPORT_READ: 'leads.report.read',

  EMPLOYEES_READ: 'employees.read',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_UPDATE: 'employees.update',
  EMPLOYEES_DELETE: 'employees.delete',
  EMPLOYEE_BRANCHES_MANAGE: 'employee.branches.manage',
  POSITIONS_READ: 'positions.read',
  POSITIONS_MANAGE: 'positions.manage',
  DEPARTMENTS_READ: 'departments.read',
  DEPARTMENTS_MANAGE: 'departments.manage',
  TASKS_READ: 'tasks.read',
  /** Tasks assigned to the caller's employee profile or created by the caller. */
  TASKS_READ_OWN: 'tasks.read_own',
  TASKS_CREATE: 'tasks.create',
  TASKS_UPDATE: 'tasks.update',
  /** Change the status of tasks assigned to the caller. */
  TASKS_UPDATE_OWN: 'tasks.update_own',
  TASKS_DELETE: 'tasks.delete',
  TASKS_ASSIGN: 'tasks.assign',
  TASKS_COMMENT: 'tasks.comment',
  TASKS_STATISTICS_READ: 'tasks.statistics.read',

  /** Own daily checklist (every staff member). */
  CHECKLISTS_READ_OWN: 'checklists.read_own',
  /** Every checklist in the caller's branches. */
  CHECKLISTS_READ: 'checklists.read',
  /** Create checklists for oneself or others, edit and stop them. */
  CHECKLISTS_MANAGE: 'checklists.manage',
  /** Send leadership announcements to staff. */
  ANNOUNCEMENTS_SEND: 'announcements.send',
  /** Congratulate employees (birthday, anniversary, achievement, thanks). */
  CONGRATULATIONS_SEND: 'congratulations.send',

  /** Own in-app notifications. */
  NOTIFICATIONS_READ: 'notifications.read',
  /** Send system notifications, edit type policies, retry deliveries. */
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  NOTIFICATION_PREFERENCES_READ: 'notification_preferences.read',
  NOTIFICATION_PREFERENCES_UPDATE: 'notification_preferences.update',
  NOTIFICATION_TEMPLATES_READ: 'notification_templates.read',
  NOTIFICATION_TEMPLATES_MANAGE: 'notification_templates.manage',
  NOTIFICATION_DELIVERY_READ: 'notification_delivery.read',
  NOTIFICATION_PROVIDERS_MANAGE: 'notification_providers.manage',

  /** Read the organization's audit trail (nobody can edit it). */
  AUDIT_READ: 'audit.read',
  /** Organization dashboard; each section also needs its own domain permission. */
  DASHBOARD_READ: 'dashboard.read',
  /** Student and attendance reports. */
  REPORTS_ACADEMIC_READ: 'reports.academic.read',
  /** Center analytics broken down by sub-center and branch. */
  ANALYTICS_CENTER_READ: 'analytics.center.read',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_DESCRIPTIONS: Record<PermissionKey, string> = {
  'organization.read': 'View organization profile',
  'organization.update': 'Edit organization profile',
  'branch.read': 'View branches',
  'branch.create': 'Create branches',
  'branch.update': 'Edit branches',
  'sub_centers.read': 'View sub-centers',
  'sub_centers.manage': 'Create, edit, freeze, activate and archive sub-centers',
  'users.read': 'View organization members',
  'users.create': 'Add organization members',
  'users.update': 'Edit organization members',
  'families.read': 'View families',
  'families.create': 'Create families',
  'families.update': 'Edit families',
  'families.delete': 'Deactivate families',
  'students.read': 'View students',
  'students.read_own': 'View students of groups the user teaches',
  'students.create': 'Create students',
  'students.update': 'Edit students and change their status',
  'students.delete': 'Mark students as left',
  'courses.read': 'View courses and levels',
  'courses.create': 'Create courses and levels',
  'courses.update': 'Edit courses and levels',
  'courses.delete': 'Deactivate courses and levels',
  'groups.read': 'View groups',
  'groups.read_own': 'View groups the user teaches',
  'groups.create': 'Create groups',
  'groups.update': 'Edit groups',
  'groups.delete': 'Cancel groups',
  'enrollments.read': 'View enrollments and student history',
  'enrollments.create': 'Enroll students into groups',
  'enrollments.update': 'Edit enrollment notes',
  'enrollments.transfer': 'Transfer students between groups',
  'enrollments.cancel': 'Cancel enrollments',
  'teachers.read': 'View teachers',
  'teachers.create': 'Create teachers',
  'teachers.update': 'Edit teachers',
  'teachers.delete': 'Deactivate teachers',
  'rooms.read': 'View rooms',
  'rooms.create': 'Create rooms',
  'rooms.update': 'Edit rooms',
  'rooms.delete': 'Deactivate rooms',
  'schedules.manage': 'Create, edit and remove group schedules',
  'attendance.read': 'View attendance and statistics',
  'attendance.read_own': 'View attendance of groups the user teaches',
  'attendance.mark': 'Mark and edit attendance',
  'attendance.mark_own': 'Mark and edit attendance of groups the user teaches',
  'attendance.mark_future': 'Mark attendance for future dates',
  'attendance.delete': 'Delete attendance marks',
  'finance.read': 'View invoices, debts and family/student finance summaries',
  'finance.invoice.create': 'Create invoices',
  'finance.invoice.update': 'Edit invoices',
  'finance.invoice.cancel': 'Cancel invoices',
  'finance.payment.read': 'View payments and refunds',
  'finance.payment.create': 'Receive payments',
  'finance.cash.read': 'View cash sessions',
  'finance.cash.open': 'Open own cash session',
  'finance.cash.close': 'Close own cash session',
  'finance.expense.read': 'View expenses',
  'finance.expense.create': 'Record expenses',
  'finance.expense.update': 'Edit expenses',
  'finance.refund.create': 'Refund payments',
  'finance.report.read': 'View financial statistics',
  'leads.read': 'View leads',
  'leads.create': 'Create leads',
  'leads.update': 'Edit leads, change status and set follow-ups',
  'leads.delete': 'Delete leads (soft delete)',
  'leads.assign': 'Assign leads to members',
  'leads.convert': 'Convert leads into families, students and enrollments',
  'leads.activity.read': 'View lead activity history',
  'leads.activity.create': 'Add lead activities',
  'lead_sources.read': 'View lead sources',
  'lead_sources.manage': 'Create, edit and deactivate lead sources',
  'lead_pipeline.read': 'View lead pipelines and stages',
  'lead_pipeline.manage': 'Create, edit and remove lead pipelines and stages',
  'leads.report.read': 'View CRM sales statistics',
  'employees.read': 'View employees',
  'employees.create': 'Create employees',
  'employees.update': 'Edit employees',
  'employees.delete': 'Terminate employees (soft delete)',
  'employee.branches.manage': 'Manage the branches an employee works in',
  'positions.read': 'View positions',
  'positions.manage': 'Create, edit and deactivate positions',
  'departments.read': 'View departments',
  'departments.manage': 'Create, edit and deactivate departments',
  'tasks.read': 'View tasks in accessible branches',
  'tasks.read_own': 'View own tasks (assigned to or created by the caller)',
  'tasks.create': 'Create tasks',
  'tasks.update': 'Edit tasks and change their status',
  'tasks.update_own': 'Change the status of own assigned tasks',
  'tasks.delete': 'Delete tasks (soft delete)',
  'tasks.assign': 'Assign tasks to employees',
  'tasks.comment': 'Comment on visible tasks',
  'tasks.statistics.read': 'View task and employee task statistics',
  'checklists.read_own': 'View and complete own daily checklist',
  'checklists.read': 'View every daily checklist in accessible branches',
  'checklists.manage': 'Create, assign, edit and stop daily checklists',
  'announcements.send': 'Send announcements to staff',
  'congratulations.send': 'Send congratulations to employees',
  'notifications.read': 'View and manage own notifications',
  'notifications.manage': 'Send system notifications, edit notification policies, retry deliveries',
  'notification_preferences.read': 'View own notification preferences',
  'notification_preferences.update': 'Change own notification preferences',
  'notification_templates.read': 'View notification templates',
  'notification_templates.manage': 'Create, edit and delete notification templates',
  'notification_delivery.read': 'View the delivery history of all notifications',
  'notification_providers.manage': 'View notification provider configuration',
  'audit.read': 'View the audit log',
  'dashboard.read': 'View the dashboard (sections follow the domain permissions)',
  'reports.academic.read': 'View student and attendance reports',
  'analytics.center.read': 'View center analytics by sub-center and branch',
};

export const ALL_PERMISSION_KEYS = Object.values(PERMISSIONS);

/**
 * Permissions a director (or anyone holding them) may hand to an individual
 * staff member on top of their role — e.g. "may create checklists".
 */
export const GRANTABLE_PERMISSIONS: readonly PermissionKey[] = [
  PERMISSIONS.CHECKLISTS_MANAGE,
  PERMISSIONS.CHECKLISTS_READ,
  PERMISSIONS.TASKS_CREATE,
  PERMISSIONS.TASKS_ASSIGN,
  PERMISSIONS.ANNOUNCEMENTS_SEND,
  PERMISSIONS.CONGRATULATIONS_SEND,
];
